trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_TOKEN: $(GITHUB_TOKEN)

jobs:
  - job: deploy
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
      - script: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
        displayName: 'Install mkdocs-material'
      - script: |
          git remote set-url origin https://$(GITHUB_TOKEN)@github.com/visionify/visionai-docs.git
          mkdocs gh-deploy --force
        displayName: 'Deploy to GitHub Pages'
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)
