site_name: VisionAI
site_description: VisionAI Toolkit - Ready to use models & vision apps
site_url: https://docs.visionify.ai/

# plugins:
#     - page-to-pdf
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Open Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
  plugins:
    - mkdocs-video
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    edit: material/pencil
  logo: img/icon-white.svg
  favicon: img/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tabs.sticky
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - content.code.annotate


repo_name: visionify/visionai
repo_url: https://github.com/visionify/visionai
edit_uri: https://github.com/visionify/visionai/edit/main/docs
copyright: Copyright &copy; 2022 - 2023 Visionify.ai

nav:
  - VisionAI:
    - Overview: index.md
    - How it works: overview/how-it-works.md
    - User Guide: overview/web-app-userguide.md
    - Scenarios: overview/scenarios.md
    - Cameras: overview/cameras.md
    - Camera Placement Guide: overview/camera-placement-guide.md
    - Azure Managed App: overview/azure-managed-app.md
    - Next steps: overview/next-steps.md
    - FAQs: overview/faqs.md

  - Scenarios:
    - Overview: scenarios/index.md

    - Hazard Warnings:
      - Overview: scenarios/hazard-warning-suite.md
      - Smoke and Fire Detection: scenarios/smoke-and-fire-detection.md
      - No smoking/no vaping: scenarios/no-smoking-hazard.md
      - Spills & leaks detection: scenarios/spills-and-leaks-hazard.md
      - Missing fire extinguisher: scenarios/missing-fire-extinguisher.md
      - Blocked exit monitoring: scenarios/blocked-exit.md
      - Equipment rust and corrosion: scenarios/rust-and-corrosion-hazard.md

    - Worker health & safety:
      - Overview: scenarios/worker-health-and-safety.md
      - PPE Detection: scenarios/ppe-detection.md
      - Working at heights: scenarios/working-at-heights.md
      - Slip, trip and fall detection: scenarios/slip-and-fall-detection.md
      - Posture & Ergonomics: scenarios/ergonomics.md
      - Spills & Leaks detection (Liquids): scenarios/spills-and-leaks.md
      - Hand-wash: scenarios/hand-wash.md
      - Confined spaces monitoring: scenarios/confined-spaces-monitoring.md

    - Occupancy Policies:
      - Overview: scenarios/occupancy-policies.md
      # - Max occupancy: scenarios/max-occupancy-count.md
      # - Restricted areas/times: scenarios/exclusion-zones.md
      # - Dwell time: scenarios/confined-spaces-monitoring.md
      # - Social distancing: scenarios/social-distance.md
      # - Station occupancy: scenarios/station-occupancy.md
      - Occupancy metrics: scenarios/occupancy-metrics.md
      # - Authorized personnel: scenarios/authorized-personnel-occupancy.md

    - Company Policies:
      - Overview: scenarios/compliance-policies.md
      - No food or drinks: scenarios/no-food-or-drinks.md
      - No phone, text, pictures: scenarios/no-phone-usage.md
      - No Smoking zones: scenarios/no-smoking.md
      - No children/visitors: scenarios/authorized-personnel.md


    - Suspicious Activity:
      - Overview: scenarios/suspicious-activity.md
      - Vandalism & property destruction: scenarios/vandalism.md
      - Firearms & knives: scenarios/firearms-and-knives.md

  
  - Privacy:
      - Overview: privacy/employee-privacy.md
      - Blur faces: privacy/blur-faces.md
      - Blur signs/text: privacy/blur-signs.md
      - Blur screens: privacy/blur-screens.md
      - Blur license plates: privacy/blur-license-plates.md
      - Obstructed camera view: privacy/obstructed-camera-view.md
  
  - Reference:
    - Overview: reference/reference.md
    - Changelog: reference/changelog.md
    - Troubleshooting: reference/troubleshooting.md
    - Notes: reference/notes.md
  - Customization:
    - Overview: custom/overview.md
    - Retrain models: custom/retraining.md
    - License: custom/licensing.md
    - FAQs: custom/faqs.md
    - Custom Services: custom/request.md
  - About:
    - About: company/about.md
    - Team: company/team.md
    - Careers: company/careers.md
    - Contact: company/contact.md
    - Privacy Policy: company/privacy-policy.md
    - Terms and Conditions: company/terms-and-conditions.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: visionify
      repo: visionai
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

extra:
  analytics:
    provider: google
    property: G-3CWR3GL7BF
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSfW7NsiBv1KCH8enZ7OJDHdQDhqY8NtUeQElm9gnRRR9pLPbw/viewform?usp=sf_link" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/visionify/visionai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/visionify
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hmurari
    - icon: fontawesome/brands/dev
      link: https://dev.to/hmurari
    - icon: fontawesome/brands/medium
      link: https://medium.com/@hmurari
    - icon: fontawesome/solid/globe
      link: https://visionify.ai
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/visionify-ai/


extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js