name: Upload scenarios.json and each_scenario_details to Azure Blob Storage

on:
  push:
    branches:
      - azure-storage-pipeline

jobs:
  upload_to_azure_blob_storage:
    runs-on: ubuntu-latest
    name: Upload scenarios.json and each_scenario_details if modified
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Check if scenarios.json or each_scenario_details are modified
        id: check-modified
        run: |
          if grep -q "scenarios.json" <<< "${{ steps.changed-files.outputs.all_changed_files }}"; then
            echo "modified=true" >> $GITHUB_ENV
          fi

          if grep -q "each_scenario_details" <<< "${{ steps.changed-files.outputs.all_changed_files }}"; then
            echo "each_scenario_details_modified=true" >> $GITHUB_ENV
          fi

      - name: Compare local and remote scenarios.json
        if: env.modified == 'true'
        id: compare-files
        run: |
          LOCAL_HASH=$(md5sum scenarios.json | awk '{ print $1 }')
          REMOTE_HASH=$(az storage blob show --account-name docsvisionify --container-name docs-images --name scenarios.json --query properties.contentSettings.contentMd5 --output tsv --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}")
          if [ "$LOCAL_HASH" != "$REMOTE_HASH" ]; then
            echo "files-different=true" >> $GITHUB_ENV
          fi

      - name: Check for changes in JSON files inside each_scenario_details folder
        if: env.each_scenario_details_modified == 'true'
        id: json-changes
        run: |
          CHANGED_JSON_FILES=$(git diff --name-only HEAD^ HEAD | grep '^each_scenario_details/.*\.json$' || true)
          if [ -n "$CHANGED_JSON_FILES" ]; then
            echo "json_files_changed=true" >> $GITHUB_ENV
          fi

      - name: Upload scenarios.json to Azure Blob Storage
        if: env.modified == 'true' && env.files-different == 'true'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Uploading scenarios.json to Azure Blob Storage..."
            az storage blob upload --account-name docsvisionify --container-name docs-images --file "scenarios.json" --name "scenarios.json" --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" --overwrite
            echo "scenarios.json uploaded successfully."

      - name: Echo no changes in JSON
        if: env.modified != 'true'
        run: echo "No changes in scenario.json file."

      - name: Upload changed JSON files in each_scenario_details to Azure Blob Storage
        if: env.each_scenario_details_modified == 'true' && env.json_files_changed == 'true'
        run: |
          echo "Uploading changed JSON files in each_scenario_details folder to Azure Blob Storage..."
          for file in $(git diff --name-only HEAD^ HEAD | grep '^each_scenario_details/.*\.json$'); do
            echo "Uploading $file to Azure Blob Storage..."
            az storage blob upload --account-name docsvisionify --container-name docs-images --file "$file" --name "$file" --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} " --overwrite
            echo "$file uploaded successfully."
          done

      - name: Echo no changes in folder
        if: env.each_scenario_details_modified != 'true'
        run: echo "No changes in each_scenario_details folder."
